App\PlayListBundle\Entity\Songs:
    type: entity
    repositoryClass: App\PlayListBundle\Repository\SongsRepository
    table: songs
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
            nullable: true
        url:
            type: string
            length: 255
            nullable: true
        artist:
            type: string
            length: 255
            nullable: true
        album:
            type: string
            length: 255
            nullable: true
        genre:
            type: string
            length: 255
            nullable: true
        directory:
            type: string
            length: 255
            nullable: true