App\PlayListBundle\Entity\Users:
  type: entity
  table: users
  id:
      id:
          type: integer
          generator: { strategy: AUTO }
  fields:
      username:
          type: string
          length: 255
      password:
          type: string
          length: 255