<?php

namespace App\PlayListBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SongsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongsRepository extends EntityRepository
{
}
