services:
     app_play_list.schedules_setter: 
         class: App\PlayListBundle\Controller\Schedules 
         arguments: ['@service_container']
#    app_play_list.example:
#        class: App\PlayListBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
