<?xml version='1.0' standalone='yes'?>
<config>
<version>0.7.0</version>
<admin_name>admin</admin_name>
<admin_pass>1d91d02a3ad86b05737ab1e6864be144</admin_pass>
<host>127.0.0.1</host>
<port>6600</port>
<pass></pass>
<output>0</output>
<template>techno-light</template>
<language>rus</language>
<volume>100</volume>
<repeat></repeat>
<random></random>
<fade>5</fade>
<rights>
<add_songs>selected</add_songs>
<start_playing>selected</start_playing>
<pause_playing>selected</pause_playing>
<set_volume>selected</set_volume>
<controll_playlist>selected</controll_playlist>
<controll_player>selected</controll_player>
<admin_relaxx></admin_relaxx>
<admin_mpd></admin_mpd>
</rights>
<plcolumns>Pos:Artist:Title:Album:Genre:Time</plcolumns>
<trcolumns>Artist:Title:Genre:Time</trcolumns>
</config>
